version: "3.9"

services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    env_file:
      - ./be/.env
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 1
    expose:
      - "8000"
    depends_on:
      - db_user
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    networks:
      - kioedu_network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: nginx_frontdend
    volumes:
      - ./fe/dist:/app/dist
    networks:
      - kioedu_network
    restart: "no" # ⭐ 빌드용이라 재시작 필요 없음

  nginx:
    image: nginx:stable-alpine
    container_name: kioquiz_nginx
    ports:
      - "8090:80"
      - "8444:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fe/dist:/usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - kioedu_network

  db_user:
    image: postgres:16
    container_name: kioquiz_db
    restart: always
    environment:
      POSTGRES_DB: kioedu
      POSTGRES_USER: rheavision
      POSTGRES_PASSWORD: 16444907
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - kioedu_network

volumes:
  media_volume:
  static_volume:
  pgdata_user:

networks:
  kioedu_network:
    external: true
