version: "3.9"

services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./be/.env
    expose:
      - "8000"
    depends_on:
      - db_user
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    networks:
      - kioedu_network

  nginx:
    image: nginx:stable-alpine
    container_name: kioquiz_nginx
    ports:
      - "8100:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fe/dist:/usr/share/nginx/html # ðŸ”¥ í•µì‹¬
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - kioedu_network

  db_user:
    image: postgres:16
    container_name: kioquiz_db
    restart: always
    environment:
      POSTGRES_DB: kioquiz
      POSTGRES_USER: kioquiz
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - kioedu_network

networks:
  kioedu_network:
    external: true

volumes:
  static_volume:
  media_volume:
  pgdata_user:
