services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./be/.env
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - kioquiz_internal

  nginx:
    build: ./fe
    container_name: kioquiz_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - backend
    networks:
      kioquiz_internal:
      proxy: # ⭐ nginx-proxy-manager 네트워크
        aliases:
          - kioquiz_nginx

  db:
    image: postgres:16
    container_name: kioquiz_db
    env_file:
      - ./be/.env
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    networks:
      - kioquiz_internal

volumes:
  media_volume:
  static_volume:
  pgdata_user:

networks:
  kioquiz_internal:
    driver: bridge
  proxy:
    external: true # ⭐ 이미 존재하는 nginx-proxy-manager 네트워크


# volumes:
#   media_volume:
#   static_volume:
#   pgdata_user:

# networks:
#   kioedu_network:
#     external: true
#   proxy:
#     external: true
