version: "3.9"

services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    # command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - ./be/.env
    expose:
      - "8000"
    depends_on:
      - db_user
    volumes:
      - media_volume:/app/media # ⭐ 추가!
      - static_volume:/app/staticfiles
    networks:
      - kioedu_network
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: pushapp_frontend
    volumes:
      - ./fe/dist:/fe/dist # ⭐ dist가 host로 복사됨
    command: ["npm", "run", "build"]
    networks:
      - kioedu_network

  nginx:
    image: nginx:stable-alpine
    container_name: kioquiz_nginx
    ports:
      - "8090:80"
      - "8444:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fe/dist:/usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/media # ⭐ nginx도 같은 볼륨 사용
    depends_on:
      - backend
    networks:
      - kioedu_network

  db_user:
    image: postgres:16
    container_name: kioquiz_db
    restart: always
    environment:
      POSTGRES_DB: kioedu
      POSTGRES_USER: rheavision
      POSTGRES_PASSWORD: 16444907
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - kioedu_network

volumes:
  media_volume:
  static_volume:
  pgdata_user:

networks:
  kioedu_network:
    external: true

# volumes:
#   media_volume:
#   static_volume:
#   pgdata_user:

# networks:
#   kioedu_network:
#     external: true
#   proxy:
#     external: true
