version: "3.9"

services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - ./be/.env
    depends_on:
      - db
    networks:
      - kioquiz

  frontend:
    build: ./fe
    container_name: kioquiz_frontend
    networks:
      - kioquiz

  nginx:
    image: nginx:stable-alpine
    container_name: kioquiz_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    networks:
      - kioquiz
      - proxy # ← 나중에 NPM이랑 연결용

  db:
    image: postgres:16
    container_name: kioquiz_db
    env_file:
      - ./be/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - kioquiz

volumes:
  postgres:
  static:
  media:

networks:
  kioquiz:
  proxy:
    external: true
