services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./be/.env
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - kioquiz_network

  nginx:
    build: ./fe
    container_name: kioquiz_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - backend
    networks:
      kioquiz_internal:
      proxy:
        aliases:
          - kioquiz_nginx # ⭐ 이 줄이 핵심

  db:
    image: postgres:16
    container_name: kioquiz_db
    env_file:
      - ./be/.env
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    networks:
      - kioquiz_network

volumes:
  media_volume:
  static_volume:
  pgdata_user:

networks:
  kioquiz_network:
    driver: bridge

# volumes:
#   media_volume:
#   static_volume:
#   pgdata_user:

# networks:
#   kioedu_network:
#     external: true
#   proxy:
#     external: true
