services:
  backend:
    build: ./be
    container_name: kioquiz_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./be/.env
    expose:
      - "8000"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - db_user
    networks:
      - kioedu_network

  nginx:
    build: ./fe # ⭐ 여기서 프론트도 같이 빌드됨
    container_name: kioquiz_nginx
    ports:
      - "8100:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - backend
    networks:
      - kioedu_network
      - proxy

  db_user:
    image: postgres:16
    container_name: kioquiz_db
    env_file:
      - ./be/.env
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - kioedu_network
