services:
  backend:
    build: ./be
    env_file:
      - ./be/.env
    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 1
    depends_on:
      - db
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    networks:
      - kioquiz_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8090:80"
      - "8444:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./fe/dist:/usr/share/nginx/html
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend
    networks:
      - kioquiz_network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: kioedu
      POSTGRES_USER: rheavision
      POSTGRES_PASSWORD: 16444907
    volumes:
      - pgdata_user:/var/lib/postgresql/data
    networks:
      - kioquiz_network

volumes:
  media_volume:
  static_volume:
  pgdata_user:

networks:
  kioquiz_network:
    driver: bridge
